[package]
name = "logic"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "logic"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }

logic_integrity = { workspace = true } 
